[functions.proxy-live-rates]
verify_jwt = false

[functions.webflow-order-handler]
verify_jwt = false

[functions.get_gateway_credentials]
enabled = true
verify_jwt = true
import_map = "./functions/get_gateway_credentials/deno.json"
entrypoint = "./functions/get_gateway_credentials/index.ts"

[functions.get_public_store_settings]
enabled = true
verify_jwt = true
import_map = "./functions/get_public_store_settings/deno.json"
entrypoint = "./functions/get_public_store_settings/index.ts"

# oauth-proxy: Public endpoint for OAuth authorize, JWT disabled.
[functions.oauth-proxy]
verify_jwt = false
