name               = "collect-proxy"
main               = "workers/collect-proxy.js"
account_id         = "7131ca40f960ede4fc7f78e697b18de4"
compatibility_date = "2025-06-21"
workers_dev        = false

# Bind this Worker to sdk.smoothr.io/collect.js
routes = [
  { pattern = "sdk.smoothr.io/collect.js", zone_id = "3fd40f4a18a7fefdd0d01e897a8afff4" }
]
