name = "smoothr-wildcard-proxy"
type = "javascript"
account_id = "7131ca40f960ede4fc7f78e697b18de4"
zone_id = "3fd40f4a18a7fefdd0d01e897a8afff4"
workers_dev = false

routes = ["*.smoothr.io/*"]

[build]
upload.format = "modules"
