name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci --ignore-scripts --loglevel verbose

      - name: Verify unscoped queries
        run: node scripts/verify-unscoped-queries.mjs

      - name: Run tests
        working-directory: storefronts
        run: npm test

      - name: Build packages
        run: npm run build
