export const AUTH_CONTAINER_SELECTOR = '[data-smoothr="auth-form"]';
export const ATTR_EMAIL = '[data-smoothr="email"]';
export const ATTR_PASSWORD = '[data-smoothr="password"]';
export const ATTR_SIGNIN = '[data-smoothr="sign-in"], [data-smoothr="login"]';
export const ATTR_REQUEST_RESET = '[data-smoothr="request-password-reset"]';
export const ATTR_RESET_PANEL = '[data-smoothr="reset-password"]';
export const ATTR_SUBMIT_RESET = '[data-smoothr="submit-reset-password"]';
export const ATTR_CONFIRM_PASSWORD = '[data-smoothr="confirm-password"]';
export const ATTR_SIGNUP = '[data-smoothr="sign-up"]';
export const RESET_ROUTE = '/reset-password';
