name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: write

# environment:
#   name: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: storefronts/package-lock.json

      - name: Install dependencies
        working-directory: storefronts
        run: npm ci

      - name: Run tests
        working-directory: storefronts
        run: npm test

      - name: Build SDK
        working-directory: storefronts
        run: npm run build

      - name: Bundle Webflow checkout
        working-directory: storefronts
        run: node scripts/bundle-webflow-checkout.js

      - name: Postbuild check
        working-directory: storefronts
        run: node scripts/check-sdk.js

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: storefronts/dist

      - name: Configure Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit deploy log
        if: success()
        run: |
          echo "- ${{ github.sha }} – $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> DEPLOY_LOG.md
          git add DEPLOY_LOG.md
          git commit -m "chore: update DEPLOY_LOG [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
