name: Build and Deploy

on:
  push:
    branches: [main]

permissions:
  contents: read

environment:
  name: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: storefronts/package-lock.json

      - name: Install dependencies
        working-directory: storefronts
        run: npm ci

      - name: Run tests
        working-directory: storefronts
        run: npm test

      - name: Build SDK
        working-directory: storefronts
        run: npm run build

      - name: Bundle Webflow checkout
        working-directory: storefronts
        run: node scripts/bundle-webflow-checkout.js

      - name: Postbuild check
        working-directory: storefronts
        run: node scripts/check-sdk.js

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: smoothr
          directory: storefronts/dist

      - name: Update deployment log
        if: success()
        run: |
          echo "- ${GITHUB_SHA} - $(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> DEPLOY_LOG.md
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add DEPLOY_LOG.md
          git commit -m "chore: update DEPLOY_LOG [skip ci]"
          git push
