name: CI

on:
  pull_request:

jobs:
  sdk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root deps
        run: npm ci

      - name: Install storefronts deps
        run: npm ci --workspace storefronts

      - name: Build storefronts (Node API via script)
        run: node scripts/build-storefronts-dist.mjs

      - name: Integrity check
        run: node scripts/assert-auth-dist-integrity.mjs

      - name: Run unit tests (storefronts)
        run: npm -w storefronts test

      - name: Run compiled dist tests (auth)
        run: npm -w storefronts run test:dist-auth
